---
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.9.0
    restart: unless-stopped
    ports:
     - "9090:9090"
    volumes:
      # Montage des volumes pour les données et la configuration
      - prometheus_data:/prometheus
      - /home/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # Point de montage configuration de prometheus
      - '--storage.tsdb.retention.time=15d' # Durée de retention des logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 124M
      
  grafana:
    image: grafana/grafana:12.4.0-20766360996
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    user: "472"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    environment:
      # SSO
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "LoutikSSO"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "${SSO_ID}" # Valeur à configurer dans le .env
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "${SSO_SECRET}" # Valeur à configurer dans le .env
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://sso.loutik.fr/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://sso.loutik.fr/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://sso.loutik.fr/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://sso.loutik.fr/application/o/grafana/end-session/"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      GF_SERVER_ROOT_URL: "https://supervision.loutik.fr"
      # Gestion d'affichage de la version sur la page de connexion
      GF_AUTH_ANONYMOUS_HIDE_VERSION: "true" # Affiche caché
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 128M

volumes:
  prometheus_data:
  grafana-data:
  grafana-conf:
